Repository SongSamTrip/mola-trip-backend, pull requests merged in 2024-05, with the labels that each got.

#6 Feat#1 Entity 설계
  src/main/java/com/mola/domain/member/Member.java
  src/main/java/com/mola/domain/member/TripFriends.java
  src/main/java/com/mola/domain/member/TripFriendsId.java
  src/main/java/com/mola/domain/trip/TripPlan.java
  src/main/java/com/mola/domain/trip/TripSpot.java
  src/main/java/com/mola/domain/trip/TripStatus.java
  src/main/resources/application.properties
  src/test/java/resources/application.properties
Labels: ✨ Feature

#8 Feat#2 : 토큰 서비스 구현
  src/main/java/com/mola/domain/member/Member.java
  src/main/java/com/mola/domain/member/MemberRepository.java
  src/main/java/com/mola/global/security/dto/LoginMemberResponse.java
  src/main/java/com/mola/global/security/service/JwtService.java
Labels: ✨ Feature

#10 Docs : 테스트코드 이슈 템플릿 추가
  .github/ISSUE_TEMPLATE/test.md
Labels: 📕 Documentation

#11 Feat#3 : 스프링 시큐리티 구현
  src/main/java/com/mola/global/config/CustomAuthenticationEntryPoint.java
  src/main/java/com/mola/global/config/JwtAuthProcessFilter.java
  src/main/java/com/mola/global/config/SecurityConfiguration.java
  src/main/java/com/mola/global/security/service/JwtProvider.java
Labels: ✨ Feature

#12 Feat#7
  src/main/java/com/mola/domain/tripFriends/TripFriends.java
  src/main/java/com/mola/domain/tripFriends/TripFriendsId.java
  src/main/java/com/mola/domain/tripFriends/TripFriendsRepository.java
  src/main/java/com/mola/domain/tripFriends/TripFriendsService.java
  src/test/java/com/mola/domain/tripFriends/TripFriendsServiceTest.java
Labels: 📋 Test

#16 Feat : 채팅 메시지 조회, 저장 구현
  src/main/java/com/mola/domain/chat/ChatMessage.java
  src/main/java/com/mola/domain/chat/ChatMessageRepository.java
  src/main/java/com/mola/domain/chat/ChatMessageService.java
Labels: ✨ Feature

#17 Test : 채팅내역 조회 테스트 코드
  src/test/java/com/mola/domain/chat/ChatMessageRepositoryTest.java
Labels: 📋 Test

#21 Feat : STOMP 인터셉터 구현
  src/main/java/com/mola/domain/chat/ChatInterceptor.java
  src/main/java/com/mola/domain/chat/WebSocketConfig.java
Labels: ✨ Feature

#22 Test : ChatInterceptor 단위테스트 작성
  src/test/java/com/mola/domain/chat/ChatInterceptorTest.java
Labels: 📋 Test

#25 Feat : 공통 에러처리 구현
  src/main/java/com/mola/domain/chat/ChatInterceptor.java
  src/main/java/com/mola/global/exception/CustomException.java
  src/main/java/com/mola/global/exception/ErrorCode.java
  src/main/java/com/mola/global/exception/ErrorResponseDto.java
  src/main/java/com/mola/global/exception/ExceptionController.java
  src/test/java/com/mola/domain/chat/ChatInterceptorTest.java
Labels: ✨ Feature

#29 Refactor : refreshToken 발급시 memberId claim 삭제
  src/main/java/com/mola/global/security/service/JwtProvider.java
Labels: 🛠️ Refactor

#30 Test : 시큐리티 관련 테스트 구현
  src/test/java/com/mola/domain/member/service/MemberAuthServiceTest.java
  src/test/java/com/mola/global/config/JwtAuthProcessFilterTest.java
  src/test/java/com/mola/global/security/service/JwtProviderTest.java
Labels: 📋 Test

#31 Feat : 채팅 기능 구현
  src/main/java/com/mola/domain/chat/ChatController.java
  src/main/java/com/mola/domain/chat/ChatInterceptor.java
  src/main/java/com/mola/domain/chat/WebSocketConfig.java
  src/main/java/com/mola/domain/trip/TripPlanRepository.java
  src/main/java/com/mola/global/config/SecurityConfiguration.java
  src/main/java/com/mola/global/config/WebMvcConfig.java
  src/test/java/com/mola/domain/chat/ChatInterceptorTest.java
  src/test/java/com/mola/domain/tripFriends/chat/ChatControllerTest.java
Labels: ✨ Feature

#36 Feat : STOMP 에러 처리 구현
  src/main/java/com/mola/domain/chat/ChatInterceptor.java
  src/main/java/com/mola/domain/chat/StompError.java
  src/main/java/com/mola/domain/chat/StompErrorHandler.java
  src/main/java/com/mola/domain/chat/WebSocketConfig.java
  src/main/java/com/mola/global/config/SecurityConfiguration.java
Labels: ✨ Feature

#41 Chore : 채팅 도메인 패키지 구조 변경
  src/main/java/com/mola/domain/chat/common/ChatInterceptor.java
  src/main/java/com/mola/domain/chat/common/WebSocketConfig.java
  src/main/java/com/mola/domain/chat/controller/ChatController.java
  src/main/java/com/mola/domain/chat/entity/ChatMessage.java
  src/main/java/com/mola/domain/chat/exception/StompError.java
  src/main/java/com/mola/domain/chat/exception/StompErrorHandler.java
  src/main/java/com/mola/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/mola/domain/chat/service/ChatMessageService.java
  src/test/java/com/mola/domain/chat/ChatInterceptorTest.java
  src/test/java/com/mola/domain/chat/ChatMessageRepositoryTest.java
Labels: Chore

#42 Feat : STOMP 헤더에서 인증정보 추출 기능 구현
  src/main/java/com/mola/domain/chat/common/ChatInterceptor.java
  src/main/java/com/mola/domain/chat/common/WebSocketConfig.java
  src/main/java/com/mola/global/security/service/JwtProvider.java
  src/test/java/com/mola/global/security/service/JwtProviderTest.java
Labels: ✨ Feature

#46 Refactor : 에러코드 확장성 향상
  src/main/java/com/mola/domain/trip/exception/TripErrorCode.java
  src/main/java/com/mola/domain/trip/exception/TripException.java
  src/main/java/com/mola/global/exception/ErrorCode.java
  src/main/java/com/mola/global/exception/ExceptionController.java
  src/main/java/com/mola/global/exception/GlobalErrorCode.java
Labels: 🛠️ Refactor

#53 Feat : 여행게시판 기능 구현
  build.gradle
  src/main/java/com/mola/domain/member/entity/Member.java
  src/main/java/com/mola/domain/tripBoard/controller/ImageController.java
  src/main/java/com/mola/domain/tripBoard/controller/TripPostController.java
  src/main/java/com/mola/domain/tripBoard/dto/TripImageDto.java
  src/main/java/com/mola/domain/tripBoard/dto/TripPostDto.java
  src/main/java/com/mola/domain/tripBoard/dto/TripPostListResponseDto.java
  src/main/java/com/mola/domain/tripBoard/dto/TripPostResponseDto.java
  src/main/java/com/mola/domain/tripBoard/dto/TripPostUpdateDto.java
  src/main/java/com/mola/domain/tripBoard/entity/Comment.java
  src/main/java/com/mola/domain/tripBoard/entity/Likes.java
  src/main/java/com/mola/domain/tripBoard/entity/TripImage.java
  src/main/java/com/mola/domain/tripBoard/entity/TripPost.java
  src/main/java/com/mola/domain/tripBoard/entity/TripPostStatus.java
  src/main/java/com/mola/domain/tripBoard/repository/TripImageRepository.java
  src/main/java/com/mola/domain/tripBoard/repository/TripPostRepository.java
  src/main/java/com/mola/domain/tripBoard/service/ImageService.java
  src/main/java/com/mola/domain/tripBoard/service/S3Service.java
  src/main/java/com/mola/domain/tripBoard/service/TripImageService.java
  src/main/java/com/mola/domain/tripBoard/service/TripPostService.java
  src/main/java/com/mola/global/auth/JwtAuthProcessFilter.java
  src/main/java/com/mola/global/config/S3Config.java
  src/main/java/com/mola/global/config/WebMvcConfig.java
  src/main/java/com/mola/global/exception/GlobalErrorCode.java
  src/test/java/com/mola/domain/tripBoard/controller/ImageControllerTest.java
  src/test/java/com/mola/domain/tripBoard/controller/TripPostControllerTest.java
  src/test/java/com/mola/domain/tripBoard/entity/CommentTest.java
  src/test/java/com/mola/domain/tripBoard/entity/LikesTest.java
  src/test/java/com/mola/domain/tripBoard/entity/TripPostTest.java
  src/test/java/com/mola/domain/tripBoard/service/TripPostServiceTest.java
  src/test/java/com/mola/fixture/Fixture.java
Labels: ✨ Feature

#55 Feat : 여행게시판 댓글 기능 구현
  src/main/java/com/mola/domain/member/dto/MemberCommentDto.java
  src/main/java/com/mola/domain/tripBoard/controller/CommentController.java
  src/main/java/com/mola/domain/tripBoard/dto/CommentDto.java
  src/main/java/com/mola/domain/tripBoard/entity/Comment.java
  src/main/java/com/mola/domain/tripBoard/repository/CommentRepository.java
  src/main/java/com/mola/domain/tripBoard/service/CommentService.java
  src/main/java/com/mola/global/exception/GlobalErrorCode.java
Labels: ✨ Feature

#59 Feat : 코드를 사용한 여행 참가
  src/main/java/com/mola/domain/trip/controller/TripPlanController.java
  src/main/java/com/mola/domain/trip/repository/TripPlanRepository.java
  src/main/java/com/mola/domain/trip/service/TripPlanService.java
  src/main/java/com/mola/global/exception/GlobalErrorCode.java
  src/test/java/com/mola/domain/trip/controller/TripPlanControllerTest.java
  src/test/java/com/mola/domain/trip/service/TripPlanServiceTest.java
  src/test/java/com/mola/global/security/service/JwtProviderTest.java
Labels: ✨ Feature, 📋 Test

#60 Feat : 여행게시글 좋아요 기능 구현
  src/main/java/com/mola/domain/member/dto/MemberTripPostDto.java
  src/main/java/com/mola/domain/member/entity/Member.java
  src/main/java/com/mola/domain/trip/entity/TripPlan.java
  src/main/java/com/mola/domain/tripBoard/controller/CommentController.java
  src/main/java/com/mola/domain/tripBoard/controller/TripPostController.java
  src/main/java/com/mola/domain/tripBoard/dto/CommentDto.java
  src/main/java/com/mola/domain/tripBoard/entity/Comment.java
  src/main/java/com/mola/domain/tripBoard/entity/Likes.java
  src/main/java/com/mola/domain/tripBoard/entity/TripImage.java
  src/main/java/com/mola/domain/tripBoard/entity/TripPost.java
  src/main/java/com/mola/domain/tripBoard/repository/LikesRepository.java
  src/main/java/com/mola/domain/tripBoard/repository/TripPostRepository.java
  src/main/java/com/mola/domain/tripBoard/service/CommentService.java
  src/main/java/com/mola/domain/tripBoard/service/LikesService.java
  src/main/java/com/mola/domain/tripBoard/service/TripPostService.java
  src/main/java/com/mola/global/exception/GlobalErrorCode.java
  src/test/java/com/mola/domain/chat/ChatInterceptorTest.java
  src/test/java/com/mola/domain/tripBoard/controller/CommentControllerTest.java
  src/test/java/com/mola/domain/tripBoard/repository/LikesRepositoryTest.java
  src/test/java/com/mola/domain/tripBoard/repository/TripPostRepositoryTest.java
  src/test/java/com/mola/domain/tripBoard/service/TripPostServiceTest.java
  src/test/java/com/mola/domain/tripFriends/chat/ChatControllerTest.java
  src/test/java/com/mola/fixture/Fixture.java
Labels: ✨ Feature

#61 Feat : 여행지 리스트 추가
  src/main/java/com/mola/domain/trip/controller/TripPlanController.java
  src/main/java/com/mola/domain/trip/dto/TripListHtmlDto.java
  src/main/java/com/mola/domain/trip/entity/TripPlan.java
  src/main/java/com/mola/domain/trip/service/TripPlanService.java
  src/main/java/com/mola/global/exception/GlobalErrorCode.java
  src/main/java/com/mola/global/util/SecurityUtil.java
Labels: ✨ Feature

#66 Feat : 여행게시판 dto 구현
  src/main/java/com/mola/domain/tripBoard/controller/ImageController.java
  src/main/java/com/mola/domain/tripBoard/dto/TripImageDto.java
  src/main/java/com/mola/domain/tripBoard/dto/TripPostDto.java
  src/main/java/com/mola/domain/tripBoard/entity/TripImage.java
  src/main/java/com/mola/domain/tripBoard/entity/TripPost.java
  src/main/java/com/mola/domain/tripBoard/service/LikesService.java
  src/main/java/com/mola/domain/tripBoard/service/TripImageService.java
  src/test/java/com/mola/domain/tripBoard/controller/ImageControllerTest.java
Labels: 🛠️ Refactor, ✨ Feature

#68 Feat : SSE 구현
  src/main/java/com/mola/domain/trip/controller/TripPlanController.java
  src/main/java/com/mola/domain/trip/dto/TripListHtmlDto.java
  src/main/java/com/mola/domain/trip/service/TripPlanService.java
  src/main/java/com/mola/global/sse/TripPlanSseRegistry.java
Labels: ✨ Feature

#71 Refactor : 여행게시판 리팩토링
  src/main/java/com/mola/domain/member/dto/MemberTripPostDto.java
  src/main/java/com/mola/domain/tripBoard/comment/service/CommentService.java
  src/main/java/com/mola/domain/tripBoard/like/repository/LikeQueryRepository.java
  src/main/java/com/mola/domain/tripBoard/like/repository/LikeQueryRepositoryImpl.java
  src/main/java/com/mola/domain/tripBoard/like/repository/LikesRepository.java
  src/main/java/com/mola/domain/tripBoard/tripImage/repository/TripImageRepository.java
  src/main/java/com/mola/domain/tripBoard/tripPost/dto/TripPostDto.java
  src/main/java/com/mola/domain/tripBoard/tripPost/entity/TripPost.java
  src/main/java/com/mola/domain/tripBoard/tripPost/repository/TripPostQueryRepository.java
  src/main/java/com/mola/domain/tripBoard/tripPost/repository/TripPostQueryRepositoryImpl.java
  src/main/java/com/mola/domain/tripBoard/tripPost/repository/TripPostRepository.java
  src/main/java/com/mola/domain/tripBoard/tripPost/service/TripPostService.java
  src/test/java/com/mola/domain/chat/ChatMessageRepositoryTest.java
  src/test/java/com/mola/domain/tripBoard/repository/LikesRepositoryTest.java
  src/test/java/com/mola/domain/tripBoard/repository/TripPostRepositoryTest.java
  src/test/java/com/mola/domain/tripBoard/service/QueryDslTripPostServiceTest.java
  src/test/java/com/mola/domain/tripBoard/service/TripPostServiceTest.java
Labels: 🛠️ Refactor

#78 Feat : 여행게시판 기능 구현
  build.gradle
  src/main/java/com/mola/domain/member/dto/MemberTripPostDto.java
  src/main/java/com/mola/domain/tripBoard/comment/controller/CommentController.java
  src/main/java/com/mola/domain/tripBoard/comment/dto/CommentDto.java
  src/main/java/com/mola/domain/tripBoard/comment/service/CommentService.java
  src/main/java/com/mola/domain/tripBoard/tripImage/entity/TripImage.java
  src/main/java/com/mola/domain/tripBoard/tripImage/repository/TripImageQueryRepository.java
  src/main/java/com/mola/domain/tripBoard/tripImage/repository/TripImageQueryRepositoryImpl.java
  src/main/java/com/mola/domain/tripBoard/tripImage/repository/TripImageRepository.java
  src/main/java/com/mola/domain/tripBoard/tripImage/service/TripImageService.java
  src/main/java/com/mola/domain/tripBoard/tripPost/controller/TripPostController.java
  src/main/java/com/mola/domain/tripBoard/tripPost/dto/TripPostListResponseDto.java
  src/main/java/com/mola/domain/tripBoard/tripPost/dto/TripPostResponseDto.java
  src/main/java/com/mola/domain/tripBoard/tripPost/entity/TripPost.java
  src/main/java/com/mola/domain/tripBoard/tripPost/repository/TripPostQueryRepository.java
  src/main/java/com/mola/domain/tripBoard/tripPost/repository/TripPostQueryRepositoryImpl.java
  src/main/java/com/mola/domain/tripBoard/tripPost/service/TripPostService.java
  src/test/java/com/mola/domain/tripBoard/controller/CommentControllerTest.java
  src/test/java/com/mola/domain/tripBoard/entity/TripPostTest.java
  src/test/java/com/mola/domain/tripBoard/repository/TripPostRepositoryTest.java
  src/test/java/com/mola/domain/tripBoard/service/QueryDslTripPostServiceTest.java
Labels: ✨ Feature

#80 Feat : 여행게시판 기능 구현
  src/main/java/com/mola/domain/tripBoard/comment/dto/CommentDto.java
  src/main/java/com/mola/domain/tripBoard/comment/entity/Comment.java
  src/main/java/com/mola/domain/tripBoard/comment/service/CommentService.java
  src/main/java/com/mola/domain/tripBoard/tripPost/repository/TripPostQueryRepositoryImpl.java
Labels: ✨ Feature

#85 Feat : 여행게시판 기능 구현
  src/main/java/com/mola/domain/chat/controller/ChatController.java
  src/main/java/com/mola/domain/chat/entity/ChatMessage.java
  src/main/java/com/mola/domain/member/repository/MemberRepository.java
  src/main/java/com/mola/domain/member/repository/MemberRepositoryCustom.java
  src/main/java/com/mola/domain/member/repository/MemberRepositoryImpl.java
  src/main/java/com/mola/domain/trip/dto/TripPlanDto.java
  src/main/java/com/mola/domain/trip/entity/TripPlan.java
  src/main/java/com/mola/domain/trip/repository/TripPlanRepository.java
  src/main/java/com/mola/domain/trip/repository/TripPlanRepositoryCustom.java
  src/main/java/com/mola/domain/trip/repository/TripPlanRepositoryImpl.java
  src/main/java/com/mola/domain/trip/service/TripPlanService.java
  src/main/java/com/mola/domain/tripBoard/comment/controller/CommentController.java
  src/main/java/com/mola/domain/tripBoard/comment/entity/Comment.java
  src/main/java/com/mola/domain/tripBoard/like/repository/LikeRepositoryCustom.java
  src/main/java/com/mola/domain/tripBoard/like/repository/LikeRepositoryImpl.java
  src/main/java/com/mola/domain/tripBoard/like/repository/LikesRepository.java
  src/main/java/com/mola/domain/tripBoard/tripImage/entity/TripImage.java
  src/main/java/com/mola/domain/tripBoard/tripImage/repository/TripImageRepository.java
  src/main/java/com/mola/domain/tripBoard/tripImage/repository/TripImageRepositoryCustom.java
  src/main/java/com/mola/domain/tripBoard/tripImage/repository/TripImageRepositoryImpl.java
  src/main/java/com/mola/domain/tripBoard/tripPost/controller/TripPostController.java
  src/main/java/com/mola/domain/tripBoard/tripPost/dto/TripPostDto.java
  src/main/java/com/mola/domain/tripBoard/tripPost/dto/TripPostResponseDto.java
  src/main/java/com/mola/domain/tripBoard/tripPost/entity/TripPost.java
  src/main/java/com/mola/domain/tripBoard/tripPost/repository/TripPostQueryRepositoryImpl.java
  src/main/java/com/mola/domain/tripBoard/tripPost/repository/TripPostRepository.java
  src/main/java/com/mola/domain/tripBoard/tripPost/repository/TripPostRepositoryCustom.java
  src/main/java/com/mola/domain/tripBoard/tripPost/service/TripPostService.java
  src/main/java/com/mola/global/util/SecurityUtil.java
  src/main/resources/application.properties
  src/test/java/com/mola/domain/tripBoard/service/TripPostServiceTest.java
Labels: ✨ Feature

#87 Refactor : TripPost 검증 로직 리팩토링
  src/main/java/com/mola/domain/tripBoard/comment/service/CommentService.java
  src/main/java/com/mola/domain/tripBoard/tripPost/repository/TripPostRepositoryCustom.java
  src/main/java/com/mola/domain/tripBoard/tripPost/repository/TripPostRepositoryImpl.java
Labels: 🛠️ Refactor

#91 Feat : BaseEntity 구현 및 적용
  src/main/java/com/mola/domain/member/entity/Member.java
  src/main/java/com/mola/domain/trip/entity/TripPlan.java
  src/main/java/com/mola/domain/tripBoard/comment/entity/Comment.java
  src/main/java/com/mola/domain/tripBoard/like/entity/Likes.java
  src/main/java/com/mola/domain/tripBoard/tripImage/entity/TripImage.java
  src/main/java/com/mola/domain/tripBoard/tripPost/entity/TripPost.java
  src/main/java/com/mola/global/BaseEntity.java
  src/main/java/com/mola/global/config/WebMvcConfig.java
Labels: ✨ Feature

#93 Feat : TripPost dto 데이터 변경
  src/main/java/com/mola/domain/chat/common/ChatInterceptor.java
  src/main/java/com/mola/domain/chat/controller/ChatController.java
  src/main/java/com/mola/domain/chat/dto/ChatMessageDto.java
  src/main/java/com/mola/domain/tripBoard/tripPost/dto/TripPostListResponseDto.java
  src/main/java/com/mola/domain/tripBoard/tripPost/repository/TripPostRepositoryImpl.java
  src/main/java/com/mola/domain/tripBoard/tripPost/service/TripPostService.java
  src/main/java/com/mola/global/config/SecurityConfiguration.java
  src/test/java/com/mola/domain/tripBoard/controller/CommentControllerTest.java
  src/test/java/com/mola/domain/tripBoard/controller/TripPostControllerTest.java
Labels: ✨ Feature

#96 Feat : 여행게시글 조회 기능구현 및 관리자 기능 구현
  src/main/java/com/mola/domain/member/controller/MemberController.java
  src/main/java/com/mola/domain/member/dto/MemberResponseDto.java
  src/main/java/com/mola/domain/member/entity/Member.java
  src/main/java/com/mola/domain/member/entity/MemberRole.java
  src/main/java/com/mola/domain/member/repository/MemberRepositoryCustom.java
  src/main/java/com/mola/domain/member/repository/MemberRepositoryImpl.java
  src/main/java/com/mola/domain/member/service/MemberService.java
  src/main/java/com/mola/domain/member/service/OAuth2UserService.java
  src/main/java/com/mola/domain/tripBoard/comment/dto/CommentDto.java
  src/main/java/com/mola/domain/tripBoard/tripImage/entity/TripImage.java
  src/main/java/com/mola/domain/tripBoard/tripPost/controller/TripPostController.java
  src/main/java/com/mola/domain/tripBoard/tripPost/dto/TripPostDto.java
  src/main/java/com/mola/domain/tripBoard/tripPost/dto/TripPostListResponseDto.java
  src/main/java/com/mola/domain/tripBoard/tripPost/dto/TripPostResponseDto.java
  src/main/java/com/mola/domain/tripBoard/tripPost/repository/TripPostRepositoryCustom.java
  src/main/java/com/mola/domain/tripBoard/tripPost/repository/TripPostRepositoryImpl.java
  src/main/java/com/mola/domain/tripBoard/tripPost/service/TripPostService.java
  src/main/java/com/mola/global/auth/CustomOAuth2User.java
  src/main/java/com/mola/global/auth/JwtAuthProcessFilter.java
  src/main/java/com/mola/global/auth/JwtProvider.java
  src/main/java/com/mola/global/config/SecurityConfiguration.java
  src/main/java/com/mola/global/util/QueryDslUtil.java
  src/test/java/com/mola/domain/member/controller/MemberControllerTest.java
  src/test/java/com/mola/domain/member/repository/MemberRepositoryTest.java
  src/test/java/com/mola/domain/tripBoard/repository/TripPostRepositoryTest.java
  src/test/java/com/mola/fixture/Fixture.java
  src/test/java/com/mola/global/security/service/JwtProviderTest.java
Labels: ✨ Feature

#98 Feat : TripPost 관리자 기능 구현
  src/main/java/com/mola/domain/tripBoard/comment/service/CommentService.java
  src/main/java/com/mola/domain/tripBoard/tripPost/entity/TripPost.java
  src/main/java/com/mola/domain/tripBoard/tripPost/service/TripPostService.java
Labels: ✨ Feature

#102 Test : 여행게시판 단위테스트 작성 및 리팩토링
  build.gradle
  src/main/java/com/mola/domain/tripBoard/comment/repository/CommentRepository.java
  src/main/java/com/mola/domain/tripBoard/comment/repository/CommentRepositoryCustom.java
  src/main/java/com/mola/domain/tripBoard/comment/repository/CommentRepositoryImpl.java
  src/main/java/com/mola/domain/tripBoard/comment/service/CommentService.java
  src/main/java/com/mola/global/config/JpaConfig.java
  src/main/java/com/mola/global/config/WebMvcConfig.java
  src/test/java/com/mola/domain/tripBoard/comment/service/CommentServiceTest.java
  src/test/java/com/mola/domain/tripBoard/repository/TripPostRepositoryTest.java
  src/test/java/com/mola/fixture/Fixture.java
Labels: 🛠️ Refactor, 📋 Test

#106 Test : 여행게시판 단위테스트 작성
  build.gradle
  src/main/java/com/mola/domain/tripBoard/comment/service/CommentService.java
  src/main/java/com/mola/domain/tripBoard/tripPost/service/TripPostService.java
  src/test/java/com/mola/domain/chat/ChatInterceptorTest.java
  src/test/java/com/mola/domain/chat/controller/ChatControllerTest.java
  src/test/java/com/mola/domain/tripBoard/comment/repository/CommentRepositoryTest.java
  src/test/java/com/mola/domain/tripBoard/comment/service/CommentServiceTest.java
  src/test/java/com/mola/domain/tripBoard/entity/CommentTest.java
  src/test/java/com/mola/domain/tripBoard/service/TripPostServiceTest.java
Labels: 📋 Test

#107 Test : Trip 생성 테스트 코드 작성
  src/main/java/com/mola/domain/trip/dto/TripPlanInfoDto.java
  src/main/java/com/mola/domain/trip/service/TripPlanService.java
  src/main/resources/application.properties
  src/test/java/com/mola/domain/trip/controller/TripPlanControllerTest.java
  src/test/java/com/mola/domain/trip/service/TripPlanServiceTest.java
Labels: 🛠️ Refactor, 📋 Test

#115 Test : 여행게시판 단위테스트 작성
  lombok.config
  src/main/java/com/mola/domain/tripBoard/like/repository/LikesRepository.java
  src/main/java/com/mola/domain/tripBoard/like/repository/LikesRepositoryCustom.java
  src/main/java/com/mola/domain/tripBoard/like/repository/LikesRepositoryImpl.java
  src/main/java/com/mola/domain/tripBoard/tripImage/service/S3Service.java
  src/main/java/com/mola/domain/tripBoard/tripImage/service/TripImageService.java
  src/main/java/com/mola/domain/tripBoard/tripPost/controller/TripPostController.java
  src/main/java/com/mola/domain/tripBoard/tripPost/repository/TripPostRepositoryImpl.java
  src/main/java/com/mola/domain/tripBoard/tripPost/service/TripPostService.java
  src/test/java/com/mola/common/TestConfig.java
  src/test/java/com/mola/domain/member/controller/MemberControllerTest.java
  src/test/java/com/mola/domain/tripBoard/controller/TripPostControllerTest.java
  src/test/java/com/mola/domain/tripBoard/repository/LikesRepositoryTest.java
  src/test/java/com/mola/domain/tripBoard/repository/TripPostRepositoryTest.java
  src/test/java/com/mola/domain/tripBoard/service/TripPostServiceTest.java
  src/test/java/com/mola/domain/tripBoard/tripImage/service/S3ServiceTest.java
  src/test/java/com/mola/domain/tripBoard/tripImage/service/TripImageServiceTest.java
Labels: 📋 Test

#117 Test : 여행게시판 단위테스트 작성
  src/main/java/com/mola/domain/tripBoard/tripImage/repository/TripImageRepository.java
  src/main/java/com/mola/domain/tripBoard/tripImage/repository/TripImageRepositoryCustom.java
  src/main/java/com/mola/domain/tripBoard/tripImage/repository/TripImageRepositoryImpl.java
  src/test/java/com/mola/domain/chat/service/ChatMessageServiceTest.java
Labels: 📋 Test

#119 Refactor : 여행게시판 리팩토링
  src/main/java/com/mola/domain/member/controller/MemberController.java
  src/main/java/com/mola/domain/tripBoard/comment/service/CommentService.java
  src/main/java/com/mola/domain/tripBoard/tripPost/controller/TripPostController.java
  src/main/java/com/mola/domain/tripBoard/tripPost/repository/TripPostRepositoryCustom.java
  src/main/java/com/mola/domain/tripBoard/tripPost/repository/TripPostRepositoryImpl.java
  src/main/java/com/mola/domain/tripBoard/tripPost/service/TripPostService.java
  src/main/java/com/mola/global/util/SecurityUtil.java
  src/test/java/com/mola/domain/tripBoard/controller/TripPostControllerTest.java
  src/test/java/com/mola/domain/tripBoard/repository/TripPostRepositoryTest.java
  src/test/java/com/mola/domain/tripBoard/service/TripPostServiceTest.java
Labels: 🛠️ Refactor
